language: python
python: 3.7.2
dist: xenial
sudo: true
install:
- pip install -r requirements.txt
- pip install pytest pytest-cov
script:
- python -m pytest --cov-report term-missing --cov-config .coveragerc --cov=./ ./tests/unit
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv -in secrets.tar.enc -out ./secrets.tar -d && tar xvf secrets.tar && sudo apt-get install -y docker-compose && docker-compose run web python3.7 -m pytest --cov-report term-missing --cov-config .coveragerc --cov=./ ./tests/integration; fi
before_deploy:
- bash docker_push
- openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv -in secrets.tar.enc -out ./secrets.tar -d && tar xvf secrets.tar
deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
