#!/bin/bash
openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv -in secrets.tar.enc -out ./secrets.tar -d
tar xvf secrets.tar
eval "$(ssh-agent -s)"
chmod 600 ./deploy_key
ssh-add ./deploy_key
ssh -i ./deploy_key -o "StrictHostKeyChecking no" mel@stella-app.northeurope.cloudapp.azure.com < script.sh
